import React, { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useAppDispatch, useAppSelector } from '@hooks';
import {
  fetchTests,
  deleteTest,
  selectMockTests,
  selectMockTestLoading,
  selectMockTestError,
  resetMockTestError,
} from '@redux/slices/mock-test.slice.js';
import {
  Button,
  Card,
  CardContent,
  Badge,
  Separator,
  toast,
} from '@components/ui/index.jsx';
import { ClipboardCheck, Clock, Award, Trash2, Calendar, BookOpen, AlertCircle } from 'lucide-react';

export default function MockTests() {
  const dispatch = useAppDispatch();
  const navigate = useNavigate();

  const tests = useAppSelector(selectMockTests);
  const loading = useAppSelector(selectMockTestLoading);
  const error = useAppSelector(selectMockTestError);

  const [deletingId, setDeletingId] = useState(null);
  const [confirmOpen, setConfirmOpen] = useState(false);

  useEffect(() => {
    dispatch(fetchTests());
  }, [dispatch]);

  useEffect(() => {
    if (error) {
      toast.error(error);
      dispatch(resetMockTestError());
    }
  }, [error, dispatch]);

  const handleDeleteClick = (id, e) => {
    e.stopPropagation();
    setDeletingId(id);
    setConfirmOpen(true);
  };

  const confirmDelete = async () => {
    if (!deletingId) return;
    try {
      await dispatch(deleteTest(deletingId)).unwrap();
      toast.success('Mock Test deleted successfully.');
    } catch (err) {
      toast.error(err.message || 'Failed to delete mock test.');
    } finally {
      setConfirmOpen(false);
      setDeletingId(null);
    }
  };

  const cancelDelete = () => {
    setConfirmOpen(false);
    setDeletingId(null);
  };

  const getDifficultyColor = (diff) => {
    switch (diff?.toLowerCase()) {
      case 'easy':
        return 'bg-emerald-50 text-emerald-700 border-emerald-150';
      case 'hard':
        return 'bg-rose-50 text-rose-700 border-rose-150';
      default:
        return 'bg-amber-50 text-amber-700 border-amber-150';
    }
  };

  return (
    <div className="space-y-6">
      {/* Header section */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h1 className="text-xl font-extrabold tracking-tight text-neutral-850">AI Mock Tests</h1>
          <p className="mt-1 text-neutral-450 text-xs font-semibold">
            Evaluate your knowledge using interactive, custom exams generated by the AI Learning Assistant.
          </p>
        </div>
        <Button
          onClick={() => navigate('/ai/chapter-explainer')}
          className="bg-brand-650 hover:bg-brand-700 text-white font-bold text-xs rounded-xl shadow-sm flex items-center gap-1.5 self-start md:self-auto"
        >
          <ClipboardCheck className="h-4 w-4" />
          Generate New Test
        </Button>
      </div>

      <Separator />

      {loading && tests.length === 0 ? (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
          {Array.from({ length: 6 }).map((_, i) => (
            <Card key={i} className="animate-pulse bg-white border border-neutral-200 shadow-sm rounded-2xl">
              <CardContent className="p-5 space-y-4">
                <div className="h-5 w-2/3 bg-neutral-200 rounded" />
                <div className="h-4 w-1/3 bg-neutral-100 rounded" />
                <div className="space-y-2 pt-2">
                  <div className="h-4 w-full bg-neutral-100 rounded" />
                  <div className="h-4 w-5/6 bg-neutral-100 rounded" />
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      ) : tests.length === 0 ? (
        <div className="text-center py-20 bg-white border border-neutral-200 rounded-2xl">
          <div className="mx-auto h-12 w-12 rounded-xl bg-neutral-50 border border-neutral-200 text-neutral-400 flex items-center justify-center mb-4">
            <ClipboardCheck className="h-6 w-6 text-neutral-400" />
          </div>
          <h3 className="text-sm font-extrabold text-neutral-800">No mock tests generated yet</h3>
          <p className="text-xs text-neutral-400 mt-1 max-w-sm mx-auto leading-relaxed">
            Go to the **AI Explainer** workspace and enter prompts like *"Class 9 Physics Mock Test"* or *"Create a React interview test"*. The AI will automatically build one for you here!
          </p>
          <Button
            onClick={() => navigate('/ai/chapter-explainer')}
            variant="outline"
            className="mt-5 text-xs font-bold border-neutral-300"
          >
            Go to AI Explainer
          </Button>
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
          {tests.map((test) => {
            const hasAttempts = test.attempts && test.attempts.length > 0;
            const latestAttempt = hasAttempts ? test.attempts[0] : null;

            return (
              <Card key={test.id} className="overflow-hidden flex flex-col border border-neutral-200/70 shadow-sm hover:border-neutral-300 transition-all bg-white rounded-2xl">
                <CardContent className="p-5 flex flex-col flex-1">
                  {/* Subject and delete */}
                  <div className="flex items-start justify-between gap-2 mb-2">
                    <Badge className="bg-brand-50 hover:bg-brand-100 text-brand-700 border-none font-bold text-[9px] py-0 px-2 rounded-md">
                      {test.subject || 'General Study'}
                    </Badge>
                    <button
                      onClick={(e) => handleDeleteClick(test.id, e)}
                      className="p-1 rounded-full text-neutral-400 hover:text-red-650 hover:bg-red-50 transition-colors shrink-0"
                      title="Delete Mock Test"
                    >
                      <Trash2 className="h-3.5 w-3.5" />
                    </button>
                  </div>

                  {/* Title */}
                  <h3 className="text-sm font-extrabold text-neutral-850 leading-snug mb-2 line-clamp-2">
                    {test.title}
                  </h3>

                  {/* Metadata info */}
                  <div className="grid grid-cols-2 gap-3 mb-4 mt-auto">
                    <div className="flex items-center gap-1.5 text-[11px] text-neutral-500 font-semibold">
                      <Clock className="h-3.5 w-3.5 text-neutral-400" />
                      <span>{test.durationMinutes} Minutes</span>
                    </div>
                    <div className="flex items-center gap-1.5 text-[11px] text-neutral-500 font-semibold">
                      <BookOpen className="h-3.5 w-3.5 text-neutral-400" />
                      <span>{test.totalQuestions} Questions</span>
                    </div>
                    <div className="flex items-center gap-1.5 text-[11px] text-neutral-500 font-semibold">
                      <Calendar className="h-3.5 w-3.5 text-neutral-400" />
                      <span>{new Date(test.createdAt).toLocaleDateString()}</span>
                    </div>
                    <div className="flex items-center gap-1.5">
                      <Badge className={`text-[9px] font-extrabold py-0.5 border ${getDifficultyColor(test.difficulty)}`}>
                        {test.difficulty}
                      </Badge>
                    </div>
                  </div>

                  <Separator className="my-3.5" />

                  {/* Latest attempt banner */}
                  {latestAttempt && (
                    <div className="mb-4 bg-brand-50/50 border border-brand-100 p-2.5 rounded-xl flex items-center justify-between text-[11px] text-brand-850 font-bold">
                      <div className="flex items-center gap-1.5">
                        <Award className="h-4 w-4 text-brand-600" />
                        <span>Best Score: {latestAttempt.percentage}%</span>
                      </div>
                      <button
                        onClick={() => navigate(`/mock-tests/attempts/${[...test.attempts].sort((a,b) => b.score - a.score)[0].id}`)}
                        className="text-[10px] text-brand-650 hover:underline uppercase tracking-wider"
                      >
                        Results
                      </button>
                    </div>
                  )}

                  {/* Action buttons */}
                  <div className="flex gap-2">
                    <Button
                      onClick={() => navigate(`/mock-tests/${test.id}`)}
                      className="flex-1 bg-brand-600 hover:bg-brand-700 text-white font-bold py-2 rounded-xl text-xs flex items-center justify-center gap-1 shadow-sm"
                    >
                      Start Test
                    </Button>
                  </div>
                </CardContent>
              </Card>
            );
          })}
        </div>
      )}

      {/* Delete confirmation modal */}
      <div className={`fixed inset-0 z-50 flex items-center justify-center p-4 ${confirmOpen ? 'block' : 'hidden'}`}>
        <div className="absolute inset-0 bg-neutral-900/40 backdrop-blur-sm" onClick={cancelDelete} />
        <Card className="relative z-10 w-full max-w-sm border border-neutral-200 shadow-xl bg-white rounded-2xl">
          <div className="p-5 space-y-4">
            <div className="flex items-start gap-3">
              <div className="p-2 rounded-full bg-red-50 text-red-650 shrink-0">
                <AlertCircle className="h-5 w-5" />
              </div>
              <div className="space-y-1">
                <h3 className="text-sm font-extrabold text-neutral-850">Delete Mock Test</h3>
                <p className="text-xs text-neutral-500 leading-relaxed">
                  Are you sure you want to delete this mock test? All details and attempt scores will be permanently deleted.
                </p>
              </div>
            </div>
            <div className="flex justify-end gap-2 pt-2">
              <Button variant="outline" size="sm" onClick={cancelDelete}>
                Cancel
              </Button>
              <Button variant="destructive" size="sm" className="bg-red-650 hover:bg-red-700 text-white font-bold" onClick={confirmDelete}>
                Delete
              </Button>
            </div>
          </div>
        </Card>
      </div>
    </div>
  );
}
